.PHONY all:
all:
	gcc -Wall -DPART1 diskinfo.c -o diskinfo
	gcc -Wall -DPART2 disklist.c -o disklist
	gcc -Wall -DPART3 diskget.c -o diskget
	gcc -Wall -DPART4 diskput.c -o diskput
.PHONY clean:
clean:
	-rm diskinfo disklist diskget diskput

